sudo: false

language: cpp

matrix:
  include :
    - os: linux
      compiler: gcc-4.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-4.9', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'libboost-all-dev', 'libtbb-dev', 'libstxxl-dev']
      install: export CXX="g++-4.9" CC="gcc-4.9"

before_script:
 - git clone https://github.com/seqan/seqan.git seqan
 - git clone https://github.com/martinjvickers/kmer_counter.git

script:
 - cd kmer_counter
 - cmake ../kmer_counter -DCMAKE_MODULE_PATH=../seqan/util/cmake -DSEQAN_INCLUDE_PATH=../seqan/include -DCMAKE_CXX_FLAGS=-std=c++14 -DCMAKE_BUILD_TYPE=Release
 - make -j2
 - ./kmer_counter -q example_data/SRR042642_10k.fastq.gz -k 3 -o example_data/SRR042642_10k_kmers_3.txt
